---
name: Release

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.release.outputs.version }}
        description: 'Version of the release'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
        working-directory: backend
    outputs:
      version: ${{ steps.version.outputs.new_version }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Calculate the new version
        uses: copapow/version-bump-package@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # required
          minor_label: 'feat'
          patch_label: 'fix'
          default_branch: 'main'

      - name: Commit package.json bump
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: 'Backend: Bump package version'

      - name: Create new GitHub Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.version.outputs.new_version }}
          generateReleaseNotes: true
          makeLatest: true
